#' Processes a tableone object to a lean, more publication-ready format
#'
#' This function takes a tableone object and performs various operations to make
#' the output more suitable for publication. It includes converting rownames to
#' column names, transferring percentage symbols, and removing unnecessary symbols.
#'
#'
#' @param table1 A tableone object generated by CreateTableOne.
#'
#' @return A data frame representing the processed tableone object.
#' @export
#'
#' @examples
#' # Assuming you already have a 'table1' object from CreateTableOne
#' # table1 <- CreateTableOne(data = your_data, strata = "strata_var", ...)
#'
#' # Call the custom function to process the tableone object
#' processed_table1 <- process_tableone(table1)
#'
#' # Now 'processed_table1' contains the result of all the operations
#'
#' @keywords tableone data preprocessing publication-ready
#' @seealso \code{\link{CreateTableOne}}
#'
#' @import tableone
#' @import dplyr
#' @author Ville Langen
stylize_tableone <- function(table1) {
  # Convert tableone object to a printable object
  table1_printed <- print(table1,
                          quote = FALSE,
                          noSpaces = TRUE,
                          test = FALSE,
                          contDigits = 1,
                          printToggle = FALSE,
                          dropEqual = TRUE,
                          explain = TRUE)

  # Convert rownames to column names
  table1_df <- as.data.frame(table1_printed) %>%
    rownames_to_column(var = "Variable")

  # Transfer the percentage symbols from 1st column to the second
  for (i in seq_len(nrow(table1_df))) {
    if (grepl("\\(SD\\)\\)$", table1_df[i, 1])) {
      next
    }
    table1_df[i, 2] <- sub("\\)$", "%)", table1_df[i, 2])
  }

  # Erase percentage, SD etc. symbols from the 1st column
  table1_df[, 1] <- sub(" \\(mean \\(SD\\)\\)$", "", table1_df[, 1])
  table1_df[, 1] <- sub(" \\(%)$", "", table1_df[, 1])

  return(table1_df)
}
