#' Processes a tableone object to a lean, more publication-ready format
#'
#' This function takes a tableone object and performs various operations to make
#' the output more suitable for publication. It includes converting rownames to
#' column names, transferring percentage symbols, removing unnecessary symbols,
#' and rounding p-values using the stylize_p function.
#'
#' @param table1 A tableone object generated by CreateTableOne.
#'
#' @return A data frame representing the processed tableone object.
#' @export
#'
#' @examples
#' # Assuming you already have a 'table1' object from CreateTableOne
#' # table1 <- CreateTableOne(data = your_data, strata = "strata_var", ...)
#'
#' # Call the custom function to process the tableone object
#' stylized_table1 <- stylize_tableone(table1)
#'
#' # Now 'stylized_table1' contains the result of all the operations
#'
#' @keywords tableone data preprocessing publication-ready
#' @seealso \code{\link{CreateTableOne}}
#'
#' @import tableone
#' @import dplyr
#' @import janitor
#' @author Ville Langén

stylize_tableone <- function(table1) {
  # Convert tableone object to a printable object
  table1_printed <- print(table1,
                          quote = FALSE,
                          noSpaces = TRUE,
                          test = TRUE,
                          contDigits = 1,
                          printToggle = FALSE,
                          dropEqual = TRUE,
                          explain = TRUE)


    # Convert rownames to column names
  table1_df <- as.data.frame(table1_printed) %>%
    rownames_to_column(var = "Variable")


  if ("p" %in% colnames(table1_df)) {
    columns_to_process <- seq(2, which(colnames(table1_df) == "p") - 1)
  } else {
    columns_to_process <- seq(2, ncol(table1_df))
  }




  # Transfer the percentage symbols from 1st column to the second
  for (i in seq_len(nrow(table1_df))) {
    if (grepl("\\(SD\\)\\)$", table1_df[i, 1])) {

      for (j in columns_to_process) {


        # Extract the text before the first "("
        before_parentheses <- sub("\\(.*", "", table1_df[i, j])

        # Extract the text inside the parentheses
        inside_parentheses <- sub(".*\\((.*)\\).*", "\\1", table1_df[i, j])

        # Combine the extracted values with " ± "
        new_value <- paste0(before_parentheses, "± ", inside_parentheses)

        # Assign the new formatted string to the second column
        table1_df[i, j] <- new_value }

      next
    }
    for (j in columns_to_process) {

      table1_df[i, j] <- sub("\\)$", "%)", table1_df[i, j])
    }
  }

  # Erase percentage, SD etc. symbols from the 1st column
  table1_df[, 1] <- sub(" \\(mean \\(SD\\)\\)$", "", table1_df[, 1])
  table1_df[, 1] <- sub(" \\(%)$", "", table1_df[, 1])

  # Process the "p" column using stylize_p function
  if ("p" %in% colnames(table1_df)) {
    p_column <- table1_df[["p"]]
    for (i in seq_len(nrow(table1_df))) {
      if (p_column[i] != "" && p_column[i] != "<0.001") {
        table1_df[i, "p"] <- stylize_p(as.numeric(p_column[i]))
      }
    }
  }

  return(table1_df)


  return(table1_df)
}




